// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025-2026 The Zapp Contributors

package xyz.justzappit.evm.crypto

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

class EciesTest {
    @Test
    fun `cross-language - Kotlin decrypts each SDK-produced fixture`() {
        // Fixtures generated by p2pdotme-sdk/scripts/generate-ecies-fixture.ts with
        // privKey = 0x01 * 32. Re-run that script to refresh if the SDK's ECIES wire
        // format ever changes.
        for ((label, plaintext, ciphertextHex) in SDK_FIXTURES) {
            val parsed = Ecies.cipherParse(ciphertextHex)
            val decrypted = Ecies.decryptWithPrivateKey(PRIV_HEX, parsed)
            assertEquals(plaintext, decrypted, "Fixture '$label' failed cross-language decrypt")
        }
    }

    @Test
    fun `Kotlin round-trip - encrypt then decrypt returns original`() {
        val msg = "hello world"
        val decrypted =
            Ecies.decryptWithPrivateKey(
                PRIV_HEX,
                Ecies.encryptWithPublicKey(PUB_HEX, msg),
            )
        assertEquals(msg, decrypted)
    }

    @Test
    fun `cipherStringify and cipherParse are inverse`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "payload")
        val parsed = Ecies.cipherParse(Ecies.cipherStringify(enc))
        assertEquals(enc.iv, parsed.iv)
        assertEquals(enc.mac, parsed.mac)
        assertEquals(enc.ciphertext, parsed.ciphertext)
        assertEquals(enc.ephemPublicKey, parsed.ephemPublicKey)
    }

    @Test
    fun `full round-trip via stringify and parse`() {
        val msg = "{\"message\":\"merchant@upi\",\"signature\":\"0xabc\"}"
        val s = Ecies.cipherStringify(Ecies.encryptWithPublicKey(PUB_HEX, msg))
        val decrypted = Ecies.decryptWithPrivateKey(PRIV_HEX, Ecies.cipherParse(s))
        assertEquals(msg, decrypted)
    }

    @Test
    fun `tampered ciphertext is rejected with MAC mismatch`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "secret")
        val tampered = enc.copy(ciphertext = "ff" + enc.ciphertext.drop(2))
        val ex =
            assertFailsWith<IllegalStateException> {
                Ecies.decryptWithPrivateKey(PRIV_HEX, tampered)
            }
        assertTrue(ex.message!!.contains("MAC mismatch"))
    }

    @Test
    fun `tampered IV is rejected with MAC mismatch`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "secret")
        val tampered = enc.copy(iv = "00".repeat(16))
        assertFailsWith<IllegalStateException> {
            Ecies.decryptWithPrivateKey(PRIV_HEX, tampered)
        }
    }

    @Test
    fun `tampered MAC is rejected`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "secret")
        val tampered = enc.copy(mac = "00".repeat(32))
        assertFailsWith<IllegalStateException> {
            Ecies.decryptWithPrivateKey(PRIV_HEX, tampered)
        }
    }

    @Test
    fun `random IV makes ciphertext non-deterministic for same plaintext`() {
        val a = Ecies.encryptWithPublicKey(PUB_HEX, "same")
        val b = Ecies.encryptWithPublicKey(PUB_HEX, "same")
        assertNotEquals(a.iv, b.iv)
        assertNotEquals(a.ephemPublicKey, b.ephemPublicKey)
        assertNotEquals(a.ciphertext, b.ciphertext)
    }

    @Test
    fun `empty plaintext round-trips`() {
        val decrypted =
            Ecies.decryptWithPrivateKey(
                PRIV_HEX,
                Ecies.encryptWithPublicKey(PUB_HEX, ""),
            )
        assertEquals("", decrypted)
    }

    @Test
    fun `unicode plaintext round-trips`() {
        val msg = "Prashant — éèê — 你好"
        val decrypted =
            Ecies.decryptWithPrivateKey(
                PRIV_HEX,
                Ecies.encryptWithPublicKey(PUB_HEX, msg),
            )
        assertEquals(msg, decrypted)
    }

    @Test
    fun `long plaintext round-trips`() {
        val msg = "A".repeat(1000)
        val decrypted =
            Ecies.decryptWithPrivateKey(
                PRIV_HEX,
                Ecies.encryptWithPublicKey(PUB_HEX, msg),
            )
        assertEquals(msg, decrypted)
    }

    @Test
    fun `ephemeral pubkey has uncompressed 04 prefix`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "test")
        assertTrue(enc.ephemPublicKey.startsWith("04"))
        assertEquals(130, enc.ephemPublicKey.length)
    }

    @Test
    fun `cipherStringify compressed prefix is 02 or 03`() {
        val s = Ecies.cipherStringify(Ecies.encryptWithPublicKey(PUB_HEX, "test"))
        val byte16 = s.substring(32, 34)
        assertTrue(byte16 == "02" || byte16 == "03", "Expected 02/03 at byte 16, got '$byte16'")
    }

    @Test
    fun `cipherParse rejects input shorter than 82 bytes`() {
        assertFailsWith<IllegalArgumentException> {
            Ecies.cipherParse("aa".repeat(40))
        }
        assertFailsWith<IllegalArgumentException> {
            Ecies.cipherParse("")
        }
    }

    @Test
    fun `wrong private key fails with MAC mismatch`() {
        val enc = Ecies.encryptWithPublicKey(PUB_HEX, "secret")
        val otherPriv = "0x" + "02".repeat(32)
        assertFailsWith<IllegalStateException> {
            Ecies.decryptWithPrivateKey(otherPriv, enc)
        }
    }

    companion object {
        const val PRIV_HEX = "0x0101010101010101010101010101010101010101010101010101010101010101"
        const val PUB_HEX =
            "1b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f" +
                "70beaf8f588b541507fed6a642c5ab42dfdf8120a7f639de5122d47a69a8e8d1"

        private data class Fixture(
            val label: String,
            val plaintext: String,
            val ciphertextHex: String,
        )

        private val SDK_FIXTURES =
            listOf(
                Fixture(
                    label = "simple_ascii",
                    plaintext = "hello world",
                    ciphertextHex =
                        "09e1b3aa1a6f42c31635c62065085d3803468fc8caea02aff1f79db99bb062d8" +
                            "a61e9f54d1a6fdd6c6b8e1670e94de7159995420aee984cc560567b144cb6002" +
                            "9ea6b29498354f5615cb1849fd0362dc0a1d31e83fa7995c38d1d36156a7c5ff" +
                            "f8",
                ),
                Fixture(
                    label = "upi_payload",
                    plaintext = "{\"message\":\"merchant@upi\",\"signature\":\"0xdeadbeef\"}",
                    ciphertextHex =
                        "3390bf70206364e984d5601ece6a22950365371662b585aabe8430f125c8208b" +
                            "37dc1fdd4526ce3567efbb90bfd0b9c3bc5c21317ecd3149bbb10169ac1f473f" +
                            "af18bc85d87d905018fdd26f328815c97fd8b75d577eed36196e9fc1d602e93e" +
                            "493cd094a934e68457f8eaedcb9db26d1a2ece5dcb9c7bb77d5da16c81334a87" +
                            "b49f9a56b06b41d81368b0486fb9f6ba2e",
                ),
                Fixture(
                    label = "unicode",
                    plaintext = "Prashant — éèê — 你好",
                    ciphertextHex =
                        "2cad3209efb583d94d9cdf4084dea9ce02f99a8f876099c96cf29b9fb515b6a0" +
                            "e0dd86b69629d4110909cab12c64ac90212e299471cd4dfc46e1abe138d1384f" +
                            "98c98985010f690eea2980931cf22494008b1168d836efdcbffee7a176c7f9c7" +
                            "22926bd1356e027540a568a1f8f5d2acfe",
                ),
                Fixture(
                    label = "empty",
                    plaintext = "",
                    ciphertextHex =
                        "63dc4c5aeca6086429f074fe4f8b65df038dde6f11875c8bfd9fc16ca59d73fa" +
                            "4e4987ee0e318984d798c9e2b015de00f504aa04212ff0389ef62795360d205f" +
                            "1f55c6a100ccd695b857f0c32ae5bf35d253d113005fe8e7a3f54f4d6a0f4481" +
                            "b4",
                ),
            )
    }
}
