package co.electriccoin.zcash.ui.common.repository

import kotlinx.coroutines.flow.MutableStateFlow

/**
 * The unsigned PCZT bytes built for a Keystone batch-signing attempt (the note-split, if needed,
 * plus every schedule transfer), retained so [applyKeystoneBatchSignatures]'s caller can match the
 * device's signatures back to the originals it built them from — these are Rust-generated byte
 * blobs, too large/inappropriate to round-trip through Compose Navigation's serialized nav args.
 *
 * When the full batch is larger than one Keystone QR round can safely hold
 * (`KEYSTONE_BATCH_MAX_ITEMS`, see `MigrationKeystoneSignVM`), it's split into multiple rounds via
 * `keystoneBatchRoundSlice` — [roundIndex] tracks which round is currently in flight (0-based),
 * and [accumulatedSplitSigned]/[accumulatedTransferSigned] carry every already-completed round's
 * results forward so the final round can hand the *whole* signed set to
 * `storeSignedNoteSplitPczt`/`storeSignedSchedulePczts`, not just its own slice. Defaulted so the
 * common single-round case (and existing tests) are unaffected.
 */
data class PendingKeystoneMigrationPczts(
    val requestId: ByteArray,
    val splitUnsignedPczt: ByteArray?,
    val transferUnsignedPczts: List<Pair<String, ByteArray>>,
    val roundIndex: Int = 0,
    val accumulatedSplitSigned: ByteArray? = null,
    val accumulatedTransferSigned: List<Pair<String, ByteArray>> = emptyList(),
)

/**
 * Transient, in-memory handoff of [PendingKeystoneMigrationPczts] between the Keystone sign screen
 * (which builds the unsigned PCZTs and the QR) and the scan screen (which applies the device's
 * signatures back to them) — sibling to [PendingMigrationScheduleRepository], same "not persisted,
 * re-enter from Confirm Transfer Plan on process death" contract.
 */
interface PendingKeystoneMigrationPcztsRepository {
    fun set(pczts: PendingKeystoneMigrationPczts)

    fun get(): PendingKeystoneMigrationPczts?

    fun clear()
}

class PendingKeystoneMigrationPcztsRepositoryImpl : PendingKeystoneMigrationPcztsRepository {
    private val pending = MutableStateFlow<PendingKeystoneMigrationPczts?>(null)

    override fun set(pczts: PendingKeystoneMigrationPczts) {
        pending.value = pczts
    }

    override fun get(): PendingKeystoneMigrationPczts? = pending.value

    override fun clear() {
        pending.value = null
    }
}
