package co.electriccoin.zcash.ui.common.repository

import kotlinx.coroutines.flow.MutableStateFlow

/**
 * The unsigned PCZT bytes built for one Keystone batch-signing attempt (the note-split, if needed,
 * plus every schedule transfer), retained so [applyKeystoneBatchSignatures]'s caller can match the
 * device's signatures back to the originals it built them from — these are Rust-generated byte
 * blobs, too large/inappropriate to round-trip through Compose Navigation's serialized nav args.
 */
data class PendingKeystoneMigrationPczts(
    val requestId: ByteArray,
    val splitUnsignedPczt: ByteArray?,
    val transferUnsignedPczts: List<Pair<String, ByteArray>>,
)

/**
 * Transient, in-memory handoff of [PendingKeystoneMigrationPczts] between the Keystone sign screen
 * (which builds the unsigned PCZTs and the QR) and the scan screen (which applies the device's
 * signatures back to them) — sibling to [PendingMigrationScheduleRepository], same "not persisted,
 * re-enter from Confirm Transfer Plan on process death" contract.
 */
interface PendingKeystoneMigrationPcztsRepository {
    fun set(pczts: PendingKeystoneMigrationPczts)

    fun get(): PendingKeystoneMigrationPczts?

    fun clear()
}

class PendingKeystoneMigrationPcztsRepositoryImpl : PendingKeystoneMigrationPcztsRepository {
    private val pending = MutableStateFlow<PendingKeystoneMigrationPczts?>(null)

    override fun set(pczts: PendingKeystoneMigrationPczts) {
        pending.value = pczts
    }

    override fun get(): PendingKeystoneMigrationPczts? = pending.value

    override fun clear() {
        pending.value = null
    }
}
