// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025-2026 The Zapp Contributors

package co.electriccoin.zcash.ui.screen.gift

import android.util.Log
import androidx.test.filters.LargeTest
import cash.z.ecc.android.bip39.Mnemonics
import cash.z.ecc.android.bip39.toEntropy
import cash.z.ecc.android.bip39.toSeed
import cash.z.ecc.android.sdk.CloseableSynchronizer
import cash.z.ecc.android.sdk.Synchronizer
import cash.z.ecc.android.sdk.WalletInitMode
import cash.z.ecc.android.sdk.exception.InitializeException
import cash.z.ecc.android.sdk.model.AccountCreateSetup
import cash.z.ecc.android.sdk.model.BlockHeight
import cash.z.ecc.android.sdk.model.FirstClassByteArray
import cash.z.ecc.android.sdk.model.ZcashNetwork
import co.electriccoin.lightwallet.client.model.LightWalletEndpoint
import co.electriccoin.zcash.ui.test.getAppContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Throwaway spike for `docs/GIFT_CARDS_PLAN.md` §7.1.
 *
 * The claim flow needs a second [Synchronizer] running against a bearer seed while the wallet's own
 * one keeps going. The SDK documents that as supported — [Synchronizer.new] throws only for a
 * duplicate network+alias, and `DatabaseCoordinator` derives per-alias file paths — but nothing had
 * shown it working on Android at runtime against a live lightwalletd. The Kotlin SDK has no global
 * write lock (unlike Swift's process-wide `DBActor`), so the open question was whether two engines
 * contend on SQLite or on the shared Sapling parameter files.
 *
 * Not part of CI: it needs the network and takes minutes. Run it against a device with
 *
 *     ./gradlew :ui-lib:connectedZcashtestnetFossDebugAndroidTest \
 *       -Pandroid.testInstrumentationRunnerArguments.class=\
 *       co.electriccoin.zcash.ui.screen.gift.IsolatedSynchronizerSpikeTest
 *
 * and read the evidence with `adb logcat -s GIFT_SPIKE`.
 */
@LargeTest
class IsolatedSynchronizerSpikeTest {
    private val context = getAppContext()

    // Named outright rather than read from resources. `zcash_is_testnet` is generated by the *app*
    // module from its product flavor, so a library module's androidTest always sees the
    // sdk-ext-lib default and silently resolves to mainnet whatever flavor was selected on the
    // command line. Mainnet is the honest test anyway — real chain, real server load — and the
    // spike only ever scans: two throwaway random seeds, no spends, no funds.
    private val network = ZcashNetwork.Mainnet

    @Test
    fun a_second_synchronizer_runs_alongside_the_first() {
        runBlocking {
            // Synchronizer.status is a plain Flow, so keep the latest value alongside each engine.
            val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())
            val walletSeed = randomSeed()
            val wallet = newSynchronizer(WALLET_ALIAS, WalletInitMode.NewWallet, walletSeed)
            val walletStatus = scope.trackStatus(wallet)
            var gift: CloseableSynchronizer? = null
            try {
                val walletLive = awaitLive(wallet, WALLET_ALIAS)
                assertTrue(walletLive, "the stand-in wallet synchronizer never reached a live state")
                val walletHeightBefore = assertNotNull(wallet.networkHeight.value)
                val walletScannedBefore = wallet.fullyScannedHeight.value

                // Second engine, distinct alias, different seed, while the first is mid-sync.
                gift = newSynchronizer(GIFT_ALIAS, WalletInitMode.RestoreWallet, randomSeed())
                val giftStatus = scope.trackStatus(gift)
                assertTrue(awaitLive(gift, GIFT_ALIAS), "the isolated gift synchronizer never reached a live state")

                observeBoth(wallet, walletStatus, gift, giftStatus)

                // The first one has to be unharmed by the second: still connected, still advancing.
                assertTrue(walletStatus.value != Synchronizer.Status.STOPPED, "wallet synchronizer stopped")
                val walletHeightAfter = assertNotNull(wallet.networkHeight.value)
                assertTrue(walletHeightAfter >= walletHeightBefore, "wallet network height went backwards")
                logProgress(walletScannedBefore, wallet.fullyScannedHeight.value)

                assertFilesAreSegregated()
                assertDuplicateAliasIsRejected(walletSeed)
                assertForeignSeedIsRejected()
            } finally {
                scope.cancel()
                gift?.close()
                wallet.close()
            }
            // Only after both are closed, or erase races the engines that hold the files open.
            delay(CLOSE_SETTLE_MILLIS)
            Log.i(TAG, "erase(wallet)=${Synchronizer.erase(context, network, WALLET_ALIAS)}")
            Log.i(TAG, "erase(gift)=${Synchronizer.erase(context, network, GIFT_ALIAS)}")
        }
    }

    private suspend fun newSynchronizer(
        alias: String,
        initMode: WalletInitMode,
        seed: ByteArray,
    ): CloseableSynchronizer {
        Log.i(TAG, "creating synchronizer alias=$alias network=${network.networkName} initMode=$initMode")
        return Synchronizer.new(
            alias = alias,
            birthday = BlockHeight.ofLatestCheckpoint(context, network),
            context = context,
            lightWalletEndpoint = endpoint(),
            setup = AccountCreateSetup(accountName = alias, keySource = null, seed = FirstClassByteArray(seed)),
            walletInitMode = initMode,
            zcashNetwork = network,
            isTorEnabled = false,
            isExchangeRateEnabled = false,
        )
    }

    private fun CoroutineScope.trackStatus(synchronizer: Synchronizer): StateFlow<Synchronizer.Status> {
        val latest = MutableStateFlow(Synchronizer.Status.INITIALIZING)
        launch { synchronizer.status.collect { latest.value = it } }
        return latest
    }

    /** Live means talking to the server: a status past INITIALIZING and a known chain tip. */
    private suspend fun awaitLive(synchronizer: Synchronizer, alias: String): Boolean =
        withTimeoutOrNull(LIVE_TIMEOUT_MILLIS) {
            synchronizer.networkHeight.first { it != null }
            synchronizer.status.first { it == Synchronizer.Status.SYNCING || it == Synchronizer.Status.SYNCED }
            Log.i(TAG, "$alias is live: tip=${synchronizer.networkHeight.value}")
            true
        } ?: false.also {
            Log.w(TAG, "$alias timed out: tip=${synchronizer.networkHeight.value}")
        }

    private suspend fun observeBoth(
        wallet: Synchronizer,
        walletStatus: StateFlow<Synchronizer.Status>,
        gift: Synchronizer,
        giftStatus: StateFlow<Synchronizer.Status>,
    ) {
        repeat(SAMPLES) { sample ->
            Log.i(
                TAG,
                "sample=$sample " +
                    "wallet[status=${walletStatus.value} tip=${wallet.networkHeight.value} " +
                    "scanned=${wallet.fullyScannedHeight.value} balances=${wallet.walletBalances.value?.size}] " +
                    "gift[status=${giftStatus.value} tip=${gift.networkHeight.value} " +
                    "scanned=${gift.fullyScannedHeight.value} balances=${gift.walletBalances.value?.size}]"
            )
            assertTrue(walletStatus.value != Synchronizer.Status.STOPPED, "wallet stopped at sample $sample")
            assertTrue(giftStatus.value != Synchronizer.Status.STOPPED, "gift stopped at sample $sample")
            delay(SAMPLE_INTERVAL_MILLIS)
        }
    }

    private fun logProgress(before: BlockHeight?, after: BlockHeight?) {
        Log.i(TAG, "wallet fullyScannedHeight before=$before after=$after")
    }

    /** Each engine must own its own files, which is what makes concurrent use safe at all. */
    private fun assertFilesAreSegregated() {
        val files =
            context.noBackupFilesDir
                .walkTopDown()
                .filter { it.isFile }
                .toList()
        val walletFiles = files.filterByAlias(WALLET_ALIAS)
        val giftFiles = files.filterByAlias(GIFT_ALIAS)
        Log.i(TAG, "wallet files=${walletFiles.map { it.name }}")
        Log.i(TAG, "gift files=${giftFiles.map { it.name }}")

        assertTrue(walletFiles.isNotEmpty(), "no per-alias files for $WALLET_ALIAS")
        assertTrue(giftFiles.isNotEmpty(), "no per-alias files for $GIFT_ALIAS")
        assertEquals(emptySet(), walletFiles.intersect(giftFiles.toSet()), "the two engines share a file")

        // Sapling params are shared on purpose — unlike iOS, a second engine does not re-download
        // them. Log what is there so a first run that does fetch them is visible.
        val params = files.filter { it.name.endsWith(".params") }
        Log.i(TAG, "sapling params=${params.map { "${it.name}:${it.length()}" }}")
    }

    /** The documented failure mode, and the reason a claim's alias must be derived per card. */
    private suspend fun assertDuplicateAliasIsRejected(seed: ByteArray) {
        val failure =
            assertFailsWith<IllegalStateException> {
                newSynchronizer(WALLET_ALIAS, WalletInitMode.ExistingWallet, seed).close()
            }
        Log.i(TAG, "duplicate alias rejected: ${failure.message}")
    }

    /**
     * A reused alias whose database belongs to a different seed fails closed, with a distinct
     * exception rather than silently opening the wrong wallet. That is the signal the claim flow
     * needs for a half-initialised or mismatched database: erase and recreate rather than proceed.
     */
    private suspend fun assertForeignSeedIsRejected() {
        val failure =
            assertFailsWith<InitializeException.SeedNotRelevant> {
                newSynchronizer(GIFT_ALIAS, WalletInitMode.ExistingWallet, randomSeed()).close()
            }
        Log.i(TAG, "foreign seed on an existing alias rejected: ${failure.message}")
    }

    private fun List<File>.filterByAlias(alias: String) = filter { it.absolutePath.contains(alias) }

    private fun randomSeed(): ByteArray {
        val code = Mnemonics.MnemonicCode(Mnemonics.WordCount.COUNT_24.toEntropy())
        return try {
            Mnemonics.MnemonicCode(code.words.joinToString(" ") { it.concatToString() }).toSeed()
        } finally {
            code.close()
        }
    }

    private fun endpoint(): LightWalletEndpoint =
        if (network == ZcashNetwork.Mainnet) {
            LightWalletEndpoint(host = "zec.rocks", port = 443, isSecure = true)
        } else {
            // Mirrors LightWalletEndpointProvider; cipherscan cannot serve gRPC (no ALPN h2).
            LightWalletEndpoint(host = "testnet.zec.rocks", port = 443, isSecure = true)
        }

    private companion object {
        const val TAG = "GIFT_SPIKE"
        const val WALLET_ALIAS = "spike_wallet"
        const val GIFT_ALIAS = "spike_gift_isolated"
        const val LIVE_TIMEOUT_MILLIS = 120_000L
        const val SAMPLES = 12
        const val SAMPLE_INTERVAL_MILLIS = 5_000L
        const val CLOSE_SETTLE_MILLIS = 2_000L
    }
}
